CREATE TABLE IF NOT EXISTS GENRE (ID IDENTITY, NAME VARCHAR(50));
CREATE TABLE IF NOT EXISTS ALBUM_TYPE (ID IDENTITY, NAME VARCHAR(50));
CREATE TABLE IF NOT EXISTS COUNTRY (ID IDENTITY, NAME VARCHAR(255));
CREATE TABLE IF NOT EXISTS BAND(
    ID IDENTITY,
    NAME VARCHAR(255),
    GENRE INT,
    COUNTRY_OF_ORIGIN INT,
    YEAR_OF_CREATION INT,
    STATUS boolean,
    FOREIGN KEY (COUNTRY_OF_ORIGIN) REFERENCES COUNTRY(id),
    FOREIGN KEY (GENRE) REFERENCES GENRE(ID)
);

CREATE TABLE IF NOT EXISTS ALBUM(
    ID IDENTITY,
    NAME VARCHAR(255),
    ALBUM_TYPE INT NOT NULL,
    RELEASE_DATE DATE,
    FOREIGN KEY (ALBUM_TYPE) REFERENCES ALBUM_TYPE(ID)
);

CREATE TABLE IF NOT EXISTS ALBUM_BAND (
    ID IDENTITY,
    ALBUM_ID INT,
    BAND_ID INT,
    UNIQUE(ALBUM_ID, BAND_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID),
    FOREIGN KEY (BAND_ID) REFERENCES BAND(ID)
);